### ISSUE TITLE
addmm_ TypeError when running vae example with cuda

### ISSUE THREAD

**Issue by hassony2** [pytorch/examples#51]
Hi ! 
First, thanks for the great work on the provided examples. I enjoyed playing around with both the mnist and the dcgan examples !
On the vae example I ran into the following issue.
It works fine on the CPU, but when I run it on a GPU device with cuda installed I obtain the following stacktrace 

```
Traceback (most recent call last):
  File "main.py", line 130, in <module>
    train(epoch)
  File "var.py", line 102, in train
    recon_batch, mu, logvar = model(data)
  File "/gpfs/workdir/hassony/virtual-python/lib/python3.5/site-packages/torch/nn/modules/module.py", line 210, in __call__
    result = self.forward(*input, **kwargs)
  File "var.py", line 67, in forward
    mu, logvar = self.encode(x.view(-1, 784))
  File "var.py", line 54, in encode
    h1 = self.relu(self.fc1(x))
  File "/gpfs/workdir/hassony/virtual-python/lib/python3.5/site-packages/torch/nn/modules/module.py", line 210, in __call__
    result = self.forward(*input, **kwargs)
  File "/gpfs/workdir/hassony/virtual-python/lib/python3.5/site-packages/torch/nn/modules/linear.py", line 53, in forward
    return self._backend.Linear()(input, self.weight, self.bias)
  File "/gpfs/workdir/hassony/virtual-python/lib/python3.5/site-packages/torch/nn/_functions/linear.py", line 10, in forward
    output.addmm_(0, 1, input, weight.t())
TypeError: addmm_ received an invalid combination of arguments - got (int, int, torch.FloatTensor, torch.cuda.FloatTensor), but expected one of:
 * (torch.FloatTensor mat1, torch.FloatTensor mat2)
 * (torch.SparseFloatTensor mat1, torch.FloatTensor mat2)
 * (float beta, torch.FloatTensor mat1, torch.FloatTensor mat2)
 * (float alpha, torch.FloatTensor mat1, torch.FloatTensor mat2)
 * (float beta, torch.SparseFloatTensor mat1, torch.FloatTensor mat2)
 * (float alpha, torch.SparseFloatTensor mat1, torch.FloatTensor mat2)
 * (float beta, float alpha, torch.FloatTensor mat1, torch.FloatTensor mat2)
 * (float beta, float alpha, torch.SparseFloatTensor mat1, torch.FloatTensor mat2)
```

The weights being a cuda tensor instead of a regular one seems to be the problem and I haven't found a way around it yet.

I would greatly appreciate any hint if you have an idea on how to fix this.

All the best,

**Comment by apaszke** [comment]
It's not a problem with weights, if you look at the order of the arguments it's `(0, 1, input, weight.t())` and it's the 3rd argument that's not on CUDA. I see the bug, the example is missing
```
if args.cuda:
    data = data.cuda()
```
in the training loop. I'll send a PR in a sec. Thanks for reporting it!

**Comment by apaszke** [comment]
Fixed in #52.

**Comment by hassony2** [comment]
Thank you for your answer and the fix ! 
I had tried to pass the data to cuda but this alone had not solved it for me.
With the additional change in the PR it works great :)

**Comment by apaszke** [comment]
Yes, the sampled noise had to be allocated on the GPU too. You can check the diff in my PR to see where was that. Thanks!
